### ISSUE TITLE
 .phoenix.js how to use?

### ISSUE THREAD

**Issue by mrdear** [metakirby5/dotfiles#2]
Sorry, I do not understand this grammar, but installed the coffee environment, but do not know how to trigger these operations

**Comment by metakirby5** [comment]
My setup is very customized to my workflow, so I won't be able to explain all of it, but I can give a general overview.

- Modifiers:
  - cmd+alt is generally for selection.
  - cmd+alt+shift is generally for movement.
  - cmd+ctrl is generally for resizing.
- Actions: combine with modifiers above for effects.
  - hjkl control windows (vim-like directions).
  - np control workspaces (next, previous).
- Quickly snap windows with cmd+alt+{q,a,z,],',/}.
- Make windows fill up available space in a direction with cmd+alt+ctrl+{h,j,k,l}.
- Refer to [this section](https://github.com/metakirby5/.dots/blob/34aca524e357e792903ab4e487dd8f187e402fa7/osx/.phoenix.js#L100) for other keybindings, most of which are activated wtih cmd+alt.

My suggestion is to take the ideas from my configuration and create your own, since we probably have different workflows. I hope this helps!

**Comment by metakirby5** [comment]
Also: the file is a configuration for [Phoenix](https://github.com/kasper/phoenix), in case you don't have it already.

**Comment by mrdear** [comment]
thanks a lot , this very helpful for me, especially cmd+alt+y is very cool.I will create my config base on yours configuration.
